### PR TITLE
Allow partial options when adding

### PR DESCRIPTION
**Pull request by ltetzlaff**

### CODE REVIEW

**Comment by sindresorhus** [comment]
All the options are already marked as optional: https://github.com/sindresorhus/p-queue/blob/master/source/options.ts What am I missing?

**Comment by ltetzlaff** [comment]
50% of generics and inheritance in Typescript still feels like it's been hacked together on a rainy sunday afternoon; generally the `= {}` should have worked right away 🤷‍♂️

I guess it's one of these things where they just check the first class in the inheritance chain or something like this..

**Comment by sindresorhus** [comment]
Is there a way we could reduce the generics usage for the options? It seems needlessly complicated.

**Comment by ltetzlaff** [comment]
Well it is a classic use case for generics since the `Queue` should be reusing its `Options` type. The baddy here seems to be the index signature but I don't really see a way of "improving" it without hacks like `(x as any)["foo"]`. Any ideas?

**Comment by sindresorhus** [comment]
@ltetzlaff I can't really think of anything better right now.

**Comment by sindresorhus** [comment]
@EricMCornelius Can you merge this?

**Comment by EricMCornelius** [comment]
@sindresorhus done - sorry for the delay

**Pull request merged**
